[Interface]
PrivateKey = +BZZ50nf8bg/BiJXhN/BA2TO8yTStEfl4GMHofcxOFc=
Address = 10.8.0.1/24
ListenPort = 51820
SaveConfig = false

[Peer]
PublicKey = 4dP/O8QCEV3ZGwRIW/QJfNuiibyjCYccZHVgQzfDRmM=
AllowedIPs = 10.8.0.2/32
