config:
  region:vpnToken:
    secure: AAABAPJY3hF/U021+w2e5VF2plHPcGDhbSGeVmM6kBij8IwqbszlQfixrvDUXDr6xceU7eY9wHPeBhLX0zIZGS/qeci0qBUFAbk3ijWI1htedd+mlf9XvlaVgK4zY1YM
  aws:region: us-east-1
  global:ecrRepoName: vpnvpn/staging
  region:imageTag: sha-517f70d
  region:desiredInstances: "1"
  region:minInstances: "1"
  region:maxInstances: "3"
  region:instanceType: t3.small
  region:adminCidr: 0.0.0.0/0
