config:
  aws:region: us-east-1
  global:ecrRepoName: vpnvpn/production
  vpnvpn-infra:controlPlaneApiUrl: https://api.vpnvpn.dev
  vpnvpn-infra:databaseUrl:
    secure: AAABAFvnCPqMjzTFgAKRe/dOSGb9rb+LwGuxszMzwK1EuzzPfSjPGxRBr4iApugGiEp6zm5NqUICM58ek5jukyRyO7ziMJi7mWLKXknbksM=
  vpnvpn-infra:controlPlaneApiKey:
    secure: AAABAE1VAnP0VWiq2MT483Knk1xoGWxSlvIh70jdu8Ybtj23eizsPLtZtaS98fp8WJlKdJ07jMp5Nr+by3d/zAJDtwULZfTsDR312G/fUlB4cAEaeb6x6g4kxYBVPu8Effm8+eU7uMkXFFz01RwsArS1Y5hnDk4fVO84sdmYKoP5MAj6sfRTtm1eVB6hV7od6YBIPRI=
  global:desktopBucket: vpnvpn-desktop-production
