config:
  region:vpnToken:
    secure: AAABAJ/5I3q2hTjQ96ICOCrM/GkyvA2XHt/VD4cmuzIquAqdUvbWBIzrY1Ve4g4xAwrS6ELYrAIvDFDT0G864l7e8mOQO+clSz9iVShj/3n54balh50YhEGCQCKzgBqN
  aws:region: us-east-1
  global:ecrRepoName: vpnvpn/production
  region:imageTag: sha-dc0b48f
  region:desiredInstances: "3"
  region:minInstances: "2"
  region:maxInstances: "10"
  region:instanceType: t3.medium
  region:adminCidr: 0.0.0.0/0
