config:
  aws:region: us-east-1
  global:ecrRepoName: vpnvpn/staging
  vpnvpn-infra:controlPlaneApiUrl: https://api.staging.vpnvpn.dev
  vpnvpn-infra:databaseUrl:
    secure: AAABABWqpU/ZMg+AdX/6Fyof5lFTUoLFIBjf8peMNInQ5/OPxwdXp+F9inAPI60AKS9hWP3L455kqCB1uPnGKkhxi7UJjl5KStUAAO5SZc0=
  vpnvpn-infra:controlPlaneApiKey:
    secure: AAABAH+olRqPdYyQXBtI/1GDNAGlxllS9PwHIX6K1fVdzt3mQM+S1Tre1z+A510fHvcXyDbYVS/n51/Ktl6uMoVbvXIajC5Idy3TAGDm5A==
  global:desktopBucket: vpnvpn-desktop-staging
  global:codeBucket: vpnvpn-lambda-deployments-staging
  global:controlPlaneCodeKey: control-plane/1764865556.zip
  global:metricsCodeKey: metrics/1764865558.zip
  global:controlPlaneImageUri: ""
  global:metricsImageUri: ""
