config:
  aws:region: us-east-1
  vpnvpn-infra:global:ecrRepoName: vpnvpn/staging
  vpnvpn-infra:region:imageTag: latest
  vpnvpn-infra:region:desiredInstances: "2"
  vpnvpn-infra:region:minInstances: "1"
  vpnvpn-infra:region:maxInstances: "10"
  vpnvpn-infra:region:instanceType: t3.medium
  vpnvpn-infra:region:adminCidr: 0.0.0.0/0
  vpnvpn-infra:region:targetSessionsPerInstance: "100"
