config:
  aws:region: us-east-1
  global:ecrRepoName: vpnvpn/staging
  vpnvpn-infra:controlPlaneApiUrl: https://api.staging.vpnvpn.dev
  vpnvpn-infra:databaseUrl:
    secure: AAABAO/1dRyeN/Vd344RdfOmxxfKdRwX+7jvY2hx1xnaV8d+lBdkRvU49iGN7o+BFn0TyhKSbVZZTT+kmO/LtPYYvwYKRbZUXNMxolUVk3E=
  vpnvpn-infra:controlPlaneApiKey:
    secure: AAABACSZ/Mnf2vyzMX/KfEtBlZoMbZcKH1R1bR2dZz8ArVjK/cY6mnr2TR2y3v5ut8ZAs114vu8fPU2Tq+WEPF3U8eZ4ilM4awGelIHRafKSPPZrq+vFiYXVweds+NqT4aDCGCXpOEKdyH+I9rAniY7ucpgLQkXZ5w39jp7z2hgA3DDzDXd9vc0zgZKqvN8=
  global:desktopBucket: vpnvpn-desktop-staging
  global:codeBucket: vpnvpn-lambda-deployments-staging
